# unbound-control stats_noreset to json
UserParameter=unbound.stats_noreset,/usr/sbin/unbound-control stats_noreset 2>&1 | /etc/zabbix/scripts/unbound/unbound-stats_to_json.pl

# get_option num-queries-per-thread
UserParameter=unbound.option.num-queries-per-thread,/usr/sbin/unbound-control get_option num-queries-per-thread 2>/dev/null

# get version of running unbound
UserParameter=unbound.version,/usr/sbin/unbound-control status 2>&1 | grep -m1 '^version:' | sed 's/^version: *//'
